// The Swiss-karting registry — typed seed data sourced from TRACKS.md and EVENTS.md.
// Read directly today (DB-free seam, like getLatestRace); the same data mirrors into
// the tracks / calendar_events tables for the DB. Wohlen is the reference entry.

import { TRACK_PATH } from '@/lib/race/sample-race';
import type { CalendarEvent, Track } from './types';

// Kartbahn Lyss — traced from OpenStreetMap raceway ways 163872055 (main loop) +
// 163872052 (Kurzanbindung connector), lat/lon projected (cos-lat corrected) into a
// normalised viewBox — the same recipe as Wohlen (see TRACKS.md). © OSM contributors.
const LYSS_PATH =
  'M 155.6 312.1 L 158.2 293.9 L 163.5 282.8 L 170.7 274.4 L 182.3 271.4 L 208 267.7 L 216.7 259.9 L 220.9 247.6 L 219 234.2 L 212.3 225.6 L 200.7 220.8 L 187.7 221.6 L 177.9 229.2 L 121.9 290.5 L 114.6 295.4 L 106.7 298.4 L 94.9 296.7 L 86.4 288.9 L 83 283.5 L 71.7 238.6 L 71.3 227.2 L 74.3 215.2 L 82.7 204.1 L 137.2 166.9 L 150.7 156.5 L 155.5 145.2 L 157.4 133.4 L 152.2 120.6 L 141.6 112 L 129.9 109.3 L 117.3 111.6 L 94.3 122.1 L 81.5 137.2 L 55.4 172.5 L 48.6 181.5 L 40.5 206.2 L 39.9 216.5 L 41.6 224.9 L 47.8 249.1 L 61.2 285.2 L 77.3 328.1 L 86.5 346.7 L 100.3 375.6 L 115.9 384 L 129.5 381.6 L 138.7 375.9 L 145.7 364.5 M 94.3 122.1 L 84.5 121.5 L 79 113.9 L 73.5 87.4 L 64.1 40.2 L 60 31 L 51.9 25.4 L 42.4 24 L 34.8 27 L 26.8 33.4 L 24 43.3 L 25.2 57.9 L 29 83 L 34.4 121.3 L 37.4 131.1 L 42.3 142.9 L 47.4 156.4 L 48.1 168.6 L 48.6 181.5';

export const TRACKS: Track[] = [
  {
    slug: 'wohlen',
    name: 'Kart-Bahn Wohlen',
    canton: 'Aargau',
    cantonCode: 'AG',
    type: 'outdoor',
    lengthM: 825,
    turns: 11,
    karts: 'petrol',
    assHomologated: true,
    opened: 1962,
    status: 'operating',
    website: 'https://www.kartbahnwohlen.ch/',
    shape: 'traced',
    layout: TRACK_PATH,
    layoutViewBox: '320 40 270 340',
  },
  {
    slug: 'lyss',
    name: 'Kartbahn Lyss',
    canton: 'Bern',
    cantonCode: 'BE',
    type: 'outdoor',
    lengthM: 750,
    karts: 'petrol',
    assHomologated: true,
    status: 'operating',
    website: 'https://kartbahnlyss.ch/',
    shape: 'traced',
    layout: LYSS_PATH,
    layoutViewBox: '0 0 245 408',
  },
  {
    slug: 'magadino',
    name: 'Pista GOKART Locarno-Magadino',
    canton: 'Ticino',
    cantonCode: 'TI',
    type: 'outdoor',
    lengthM: 620,
    turns: 10,
    karts: 'petrol',
    assHomologated: true,
    status: 'operating',
    website: 'https://www.karts.ch/',
    shape: 'external',
  },
  {
    slug: 'spreitenbach',
    name: 'Kartbahn Spreitenbach',
    canton: 'Aargau',
    cantonCode: 'AG',
    type: 'both',
    lengthM: 420,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://spreitenbach.kart.ch/',
    shape: 'external',
  },
  {
    slug: 'cinema8',
    name: 'Cinema 8 – Indoor-Kartbahn',
    canton: 'Aargau',
    cantonCode: 'AG',
    type: 'indoor',
    lengthM: 370,
    karts: 'electric',
    assHomologated: false,
    opened: 2022,
    status: 'operating',
    website: 'https://cinema8.ch/',
    shape: 'none',
  },
  {
    slug: 'tempodrom',
    name: 'Tempodrom Winterthur',
    canton: 'Zürich',
    cantonCode: 'ZH',
    type: 'both',
    lengthM: 500,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://winterthur.kart.ch/',
    shape: 'none',
  },
  {
    slug: 'kart-basel',
    name: 'Kart Basel',
    canton: 'Basel-Stadt',
    cantonCode: 'BS',
    type: 'indoor',
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://kartbasel.ch/',
    shape: 'external',
  },
  {
    slug: 'race-inn',
    name: 'Race-Inn Roggwil',
    canton: 'Bern',
    cantonCode: 'BE',
    type: 'indoor',
    lengthM: 641,
    karts: 'petrol + electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://www.race-inn.ch/',
    shape: 'none',
  },
  {
    slug: 'rigi-race',
    name: 'Rigi-Race Brunnen',
    canton: 'Schwyz',
    cantonCode: 'SZ',
    type: 'indoor',
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    shape: 'none',
  },
  {
    slug: 'swiss-holiday-park',
    name: 'Swiss Holiday Park',
    canton: 'Schwyz',
    cantonCode: 'SZ',
    type: 'outdoor',
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://www.swissholidaypark.ch/',
    shape: 'none',
  },
  {
    slug: 'sulgen',
    name: 'Kartbahn Sulgen',
    canton: 'Thurgau',
    cantonCode: 'TG',
    type: 'both',
    lengthM: 550,
    karts: 'petrol',
    assHomologated: false,
    status: 'operating',
    website: 'https://kartbahn-sulgen.ch/',
    shape: 'none',
  },
  {
    slug: 'arbopark',
    name: 'ArboPark Kartbahn',
    canton: 'Thurgau',
    cantonCode: 'TG',
    type: 'indoor',
    lengthM: 240,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://www.arbopark.ch/',
    shape: 'external',
  },
  {
    slug: 'fimmelsberg',
    name: 'Kartbahn Fimmelsberg',
    canton: 'Thurgau',
    cantonCode: 'TG',
    type: 'indoor',
    lengthM: 420,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://kartbahn-fimmelsberg.ch/',
    shape: 'none',
  },
  {
    slug: 'battlekart',
    name: 'BattleKart Altstätten',
    canton: 'St. Gallen',
    cantonCode: 'SG',
    type: 'indoor',
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://www.battlekart.com/de/altstaetten-sg',
    shape: 'none',
  },
  {
    slug: 'cazis',
    name: 'OutdoorKart Graubünden',
    canton: 'Graubünden',
    cantonCode: 'GR',
    type: 'outdoor',
    lengthM: 800,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://outdoorkart.ch/',
    shape: 'none',
  },
  {
    slug: 'vuiteboeuf',
    name: 'Karting de Vuiteboeuf',
    canton: 'Vaud',
    cantonCode: 'VD',
    type: 'both',
    lengthM: 1600,
    karts: 'petrol',
    assHomologated: false,
    status: 'operating',
    website: 'https://www.kartingvuiteboeuf.ch/',
    shape: 'external',
  },
  {
    slug: 'payerneland',
    name: 'Karting Payerneland',
    canton: 'Vaud',
    cantonCode: 'VD',
    type: 'both',
    lengthM: 1050,
    assHomologated: false,
    status: 'operating',
    website: 'https://payerneland.ch/',
    shape: 'none',
  },
  {
    slug: 'bassecourt',
    name: 'Karting de Bassecourt',
    canton: 'Jura',
    cantonCode: 'JU',
    type: 'both',
    lengthM: 600,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://karting-bassecourt.ch/',
    shape: 'none',
  },
  {
    slug: 'karting-valais',
    name: 'Karting Valais',
    canton: 'Valais',
    cantonCode: 'VS',
    type: 'both',
    lengthM: 600,
    karts: 'electric',
    assHomologated: false,
    opened: 2027,
    status: 'construction',
    website: 'https://karting-valais.ch/',
    shape: 'none',
  },
];

// The reference event — Kartbahn Wohlen 2H GP, six rounds in 2026. R3 is the race
// we hold timing for; the rest are scheduled (no data yet).
const WOHLEN_2H_GP: CalendarEvent[] = [
  {
    slug: 'wohlen-2hgp-r1',
    name: 'Wohlen 2h GP — R1',
    trackSlug: 'wohlen',
    date: '2026-04-19',
    format: '2 h team endurance',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'wohlen-2hgp-r2',
    name: 'Wohlen 2h GP — R2 (twilight)',
    trackSlug: 'wohlen',
    date: '2026-05-23',
    format: '2 h team endurance',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'wohlen-2hgp-r3',
    name: 'Wohlen 2h GP — R3',
    trackSlug: 'wohlen',
    date: '2026-06-28',
    format: '2 h team endurance',
    entry: 'open',
    hasData: true,
  },
  {
    slug: 'wohlen-2hgp-r4',
    name: 'Wohlen 2h GP — R4',
    trackSlug: 'wohlen',
    date: '2026-08-23',
    format: '2 h team endurance',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'wohlen-2hgp-r5',
    name: 'Wohlen 2h GP — R5',
    trackSlug: 'wohlen',
    date: '2026-09-27',
    format: '2 h team endurance',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'wohlen-2hgp-r6',
    name: 'Wohlen 2h GP — R6',
    trackSlug: 'wohlen',
    date: '2026-10-18',
    format: '2 h team endurance',
    entry: 'open',
    hasData: false,
  },
];

export const EVENTS: CalendarEvent[] = [
  ...WOHLEN_2H_GP,
  {
    slug: 'payerne-summer-r1',
    name: 'Payerneland Summer Endurance — R1',
    trackSlug: 'payerneland',
    date: '2026-05-23',
    format: '2 h 30 team',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'magadino-trophy-final',
    name: 'Magadino Rental Kart Trophy — Final',
    trackSlug: 'magadino',
    date: '2026-10-17',
    format: 'solo rental sprint',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'kappelen-12h',
    name: 'Kappelen 12-Hour Endurance',
    trackSlug: 'lyss',
    date: '2026-04-26',
    format: '12 h team',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'locarno-km-r1',
    name: 'Locarno Kart Master — R1',
    trackSlug: 'magadino',
    date: '2026-06-07',
    format: 'regional championship',
    entry: 'licensed',
    spectatorOpen: true,
    hasData: false,
  },
  {
    slug: 'autobau-skm-finale',
    name: 'autobau Swiss Kart Championship — finale',
    trackSlug: 'wohlen',
    date: '2026-10-10',
    format: 'national title',
    entry: 'licensed',
    hasData: false,
  },
];

export const trackBySlug = (slug: string): Track | undefined => TRACKS.find((t) => t.slug === slug);
export const eventsForTrack = (slug: string): CalendarEvent[] =>
  EVENTS.filter((e) => e.trackSlug === slug);
