// The Swiss-karting registry — typed seed data sourced from TRACKS.md and EVENTS.md.
// Read directly today (DB-free seam, like getLatestRace); the same data mirrors into
// the tracks / calendar_events tables for the DB. Wohlen is the reference entry.

import { TRACK_PATH } from '@/lib/race/sample-race';
import type { CalendarEvent, Track } from './types';

export const TRACKS: Track[] = [
  {
    slug: 'wohlen',
    name: 'Kart-Bahn Wohlen',
    canton: 'Aargau',
    cantonCode: 'AG',
    type: 'outdoor',
    lengthM: 825,
    turns: 11,
    karts: 'petrol',
    assHomologated: true,
    opened: 1962,
    status: 'operating',
    website: 'https://www.kartbahnwohlen.ch/',
    shape: 'traced',
    layout: TRACK_PATH,
  },
  {
    slug: 'lyss',
    name: 'Kartbahn Lyss',
    canton: 'Bern',
    cantonCode: 'BE',
    type: 'outdoor',
    lengthM: 750,
    karts: 'petrol',
    assHomologated: true,
    status: 'operating',
    website: 'https://kartbahnlyss.ch/',
    shape: 'none',
  },
  {
    slug: 'magadino',
    name: 'Pista GOKART Locarno-Magadino',
    canton: 'Ticino',
    cantonCode: 'TI',
    type: 'outdoor',
    lengthM: 620,
    turns: 10,
    karts: 'petrol',
    assHomologated: true,
    status: 'operating',
    website: 'https://www.karts.ch/',
    shape: 'external',
  },
  {
    slug: 'spreitenbach',
    name: 'Kartbahn Spreitenbach',
    canton: 'Aargau',
    cantonCode: 'AG',
    type: 'both',
    lengthM: 420,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://spreitenbach.kart.ch/',
    shape: 'external',
  },
  {
    slug: 'cinema8',
    name: 'Cinema 8 – Indoor-Kartbahn',
    canton: 'Aargau',
    cantonCode: 'AG',
    type: 'indoor',
    lengthM: 370,
    karts: 'electric',
    assHomologated: false,
    opened: 2022,
    status: 'operating',
    website: 'https://cinema8.ch/',
    shape: 'none',
  },
  {
    slug: 'tempodrom',
    name: 'Tempodrom Winterthur',
    canton: 'Zürich',
    cantonCode: 'ZH',
    type: 'both',
    lengthM: 500,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://winterthur.kart.ch/',
    shape: 'none',
  },
  {
    slug: 'kart-basel',
    name: 'Kart Basel',
    canton: 'Basel-Stadt',
    cantonCode: 'BS',
    type: 'indoor',
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://kartbasel.ch/',
    shape: 'external',
  },
  {
    slug: 'race-inn',
    name: 'Race-Inn Roggwil',
    canton: 'Bern',
    cantonCode: 'BE',
    type: 'indoor',
    lengthM: 641,
    karts: 'petrol + electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://www.race-inn.ch/',
    shape: 'none',
  },
  {
    slug: 'rigi-race',
    name: 'Rigi-Race Brunnen',
    canton: 'Schwyz',
    cantonCode: 'SZ',
    type: 'indoor',
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    shape: 'none',
  },
  {
    slug: 'swiss-holiday-park',
    name: 'Swiss Holiday Park',
    canton: 'Schwyz',
    cantonCode: 'SZ',
    type: 'outdoor',
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://www.swissholidaypark.ch/',
    shape: 'none',
  },
  {
    slug: 'sulgen',
    name: 'Kartbahn Sulgen',
    canton: 'Thurgau',
    cantonCode: 'TG',
    type: 'both',
    lengthM: 550,
    karts: 'petrol',
    assHomologated: false,
    status: 'operating',
    website: 'https://kartbahn-sulgen.ch/',
    shape: 'none',
  },
  {
    slug: 'arbopark',
    name: 'ArboPark Kartbahn',
    canton: 'Thurgau',
    cantonCode: 'TG',
    type: 'indoor',
    lengthM: 240,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://www.arbopark.ch/',
    shape: 'external',
  },
  {
    slug: 'fimmelsberg',
    name: 'Kartbahn Fimmelsberg',
    canton: 'Thurgau',
    cantonCode: 'TG',
    type: 'indoor',
    lengthM: 420,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://kartbahn-fimmelsberg.ch/',
    shape: 'none',
  },
  {
    slug: 'battlekart',
    name: 'BattleKart Altstätten',
    canton: 'St. Gallen',
    cantonCode: 'SG',
    type: 'indoor',
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://www.battlekart.com/de/altstaetten-sg',
    shape: 'none',
  },
  {
    slug: 'cazis',
    name: 'OutdoorKart Graubünden',
    canton: 'Graubünden',
    cantonCode: 'GR',
    type: 'outdoor',
    lengthM: 800,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://outdoorkart.ch/',
    shape: 'none',
  },
  {
    slug: 'vuiteboeuf',
    name: 'Karting de Vuiteboeuf',
    canton: 'Vaud',
    cantonCode: 'VD',
    type: 'both',
    lengthM: 1600,
    karts: 'petrol',
    assHomologated: false,
    status: 'operating',
    website: 'https://www.kartingvuiteboeuf.ch/',
    shape: 'external',
  },
  {
    slug: 'payerneland',
    name: 'Karting Payerneland',
    canton: 'Vaud',
    cantonCode: 'VD',
    type: 'both',
    lengthM: 1050,
    assHomologated: false,
    status: 'operating',
    website: 'https://payerneland.ch/',
    shape: 'none',
  },
  {
    slug: 'bassecourt',
    name: 'Karting de Bassecourt',
    canton: 'Jura',
    cantonCode: 'JU',
    type: 'both',
    lengthM: 600,
    karts: 'electric',
    assHomologated: false,
    status: 'operating',
    website: 'https://karting-bassecourt.ch/',
    shape: 'none',
  },
  {
    slug: 'karting-valais',
    name: 'Karting Valais',
    canton: 'Valais',
    cantonCode: 'VS',
    type: 'both',
    lengthM: 600,
    karts: 'electric',
    assHomologated: false,
    opened: 2027,
    status: 'construction',
    website: 'https://karting-valais.ch/',
    shape: 'none',
  },
];

// The reference event — Kartbahn Wohlen 2H GP, six rounds in 2026. R3 is the race
// we hold timing for; the rest are scheduled (no data yet).
const WOHLEN_2H_GP: CalendarEvent[] = [
  {
    slug: 'wohlen-2hgp-r1',
    name: 'Wohlen 2h GP — R1',
    trackSlug: 'wohlen',
    date: '2026-04-19',
    format: '2 h team endurance',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'wohlen-2hgp-r2',
    name: 'Wohlen 2h GP — R2 (twilight)',
    trackSlug: 'wohlen',
    date: '2026-05-23',
    format: '2 h team endurance',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'wohlen-2hgp-r3',
    name: 'Wohlen 2h GP — R3',
    trackSlug: 'wohlen',
    date: '2026-06-28',
    format: '2 h team endurance',
    entry: 'open',
    hasData: true,
  },
  {
    slug: 'wohlen-2hgp-r4',
    name: 'Wohlen 2h GP — R4',
    trackSlug: 'wohlen',
    date: '2026-08-23',
    format: '2 h team endurance',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'wohlen-2hgp-r5',
    name: 'Wohlen 2h GP — R5',
    trackSlug: 'wohlen',
    date: '2026-09-27',
    format: '2 h team endurance',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'wohlen-2hgp-r6',
    name: 'Wohlen 2h GP — R6',
    trackSlug: 'wohlen',
    date: '2026-10-18',
    format: '2 h team endurance',
    entry: 'open',
    hasData: false,
  },
];

export const EVENTS: CalendarEvent[] = [
  ...WOHLEN_2H_GP,
  {
    slug: 'payerne-summer-r1',
    name: 'Payerneland Summer Endurance — R1',
    trackSlug: 'payerneland',
    date: '2026-05-23',
    format: '2 h 30 team',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'magadino-trophy-final',
    name: 'Magadino Rental Kart Trophy — Final',
    trackSlug: 'magadino',
    date: '2026-10-17',
    format: 'solo rental sprint',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'kappelen-12h',
    name: 'Kappelen 12-Hour Endurance',
    trackSlug: 'lyss',
    date: '2026-04-26',
    format: '12 h team',
    entry: 'open',
    hasData: false,
  },
  {
    slug: 'locarno-km-r1',
    name: 'Locarno Kart Master — R1',
    trackSlug: 'magadino',
    date: '2026-06-07',
    format: 'regional championship',
    entry: 'licensed',
    spectatorOpen: true,
    hasData: false,
  },
  {
    slug: 'autobau-skm-finale',
    name: 'autobau Swiss Kart Championship — finale',
    trackSlug: 'wohlen',
    date: '2026-10-10',
    format: 'national title',
    entry: 'licensed',
    hasData: false,
  },
];

export const trackBySlug = (slug: string): Track | undefined => TRACKS.find((t) => t.slug === slug);
export const eventsForTrack = (slug: string): CalendarEvent[] =>
  EVENTS.filter((e) => e.trackSlug === slug);
